---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: repos.godoc.rpflynn22.io
spec:
  group: godoc.rpflynn22.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                repo:
                  type: string
                dnsParent:
                  type: string
                albSecurityGroup:
                  type: string
                githubPATSecret:
                  type: object
                  properties:
                    name:
                      type: string
                    key:
                      type: string
            status:
              type: object
              properties:
                ready:
                  type: boolean
  names:
    kind: Repo
    plural: repos
    singular: repo
  scope: Namespaced
