apiVersion: godoc.rpflynn22.io/v1alpha1
kind: Repo
metadata:
  name: test
spec:
  goConfig:
    repo: github.com/rpflynn22/private-test-0
  githubCredentials:
    username: rpflynn22
    personalAccessTokenSecret:
      name: github
      key: pat
  albConfig:
    dnsParent: "godoc.example.com"
    securityGroup: "sg-test"
