{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "godoc-operator.serviceAccountName" . }}
  labels:
    {{- include "godoc-operator.labels" . | nindent 4 }}
{{- end }}
