---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: repos.godoc.rpflynn22.io
spec:
  group: godoc.rpflynn22.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - goConfig
              - githubCredentials
              properties:
                goConfig:
                  type: object
                  required:
                  - repo
                  properties:
                    repo:
                      type: string
                    goPrivatePattern:
                      type: string
                    moduleVersion:
                      type: string
                    importPath:
                      type: string
                githubCredentials:
                  type: object
                  required:
                  - username
                  - personalAccessTokenSecret
                  properties:
                    username:
                      type: string
                    personalAccessTokenSecret:
                      type: object
                      required:
                      - name
                      - key
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                awsAlbConfig:
                  type: object
                  required:
                  - securityGroup
                  properties:
                    securityGroup:
                      type: string
                    certificateArn:
                      type: string
                dnsParent:
                  type: string
            status:
              type: object
              properties:
                ready:
                  type: boolean
  names:
    kind: Repo
    plural: repos
    singular: repo
  scope: Namespaced
